### ISSUE TITLE
How to navigate a screen without NavBar?

### ISSUE THREAD

**Issue by TharinduKetipe** [BilalShahid13/PersistentBottomNavBar#29] opened 2020-06-02 15:39 UTC
Hi!
I have developed an application which contains login screen. Login screen doesn't contains a bottom navigation bar. Once user logged in, from Home Screen onwards I'm showing bottom navigation bar. But once user logged out I'm redirecting user to the Login Screen. But bottom navigation bar is still remains in the login screen as well. I'm using the following function for logout navigation.
 ```
Navigator.of(context).pushAndRemoveUntil(
                  CupertinoPageRoute(
                    builder: (BuildContext context) {
                      return LoginPage(title: 'Sign In');
                    },
                  ),
                  (_) => true,
                );
```
How do I navigate to Login Screen without bottom navigation bar?

**Comment by BilalShahid13** [comment] 2020-06-03 17:07
This is a duplicate of this [issue](https://github.com/BilalShahid13/PersistentBottomNavBar/issues/23). Please check my response there as the answer there applies to your issue as well. Thank you.

**Closed** 2020-07-22 12:15 UTC
